# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Dopetrope"
license = "CC3"
licenselink = "http://creativecommons.org/licenses/by/3.0/"
description = ""
homepage = "https://github.com/PierrePaul/hugo-dopetrope"
tags = []
features = []
min_version = 0.18

[author]
  name = "Pierre Paul Lefebvre"
  homepage = "https://www.pierre-paul.com"

[original]
  name = "Dopetrope"
  homepage = "https://html5up.net/dopetrope"
